channels:
  - schrodinger
  - conda-forge
  - defaults
dependencies:
  - openbabel
  - openmm
  - pdbfixer
  - py3dmol
  - pymol
  - rdkit
  - pip
  - pip:
    - mdanalysis
    - meeko
    - networkx
    - prolif
    - vina
