name: Jupyter_Dock
channels:
  - schrodinger
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - alsa-lib
  - attrs
  - backcall=
  - backports
  - backports.functools_lru_cache
  - bleach
  - boost
  - boost-cpp=
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cached-property
  - cairo
  - certifi=
  - cffi
  - chardet
  - charset-normalizer
  - cryptography
  - cudatoolkit
  - curl
  - cycler
  - cython
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - fftw
  - fontconfig
  - freetype
  - gettext
  - glew
  - glib
  - glib-tools
  - greenlet
  - gst-plugins-base
  - gstreamer
  - h5py
  - hdf4
  - hdf5
  - icu
  - idna=
  - importlib-metadata
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jbig
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab_widgets
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libblas
  - libcblas
  - libclang
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libevent
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran4
  - libglib
  - libglu
  - libgomp
  - libholoplaycore
  - libiconv
  - liblapack
  - libllvm11
  - libnetcdf
  - libnghttp2
  - libogg
  - libopenblas
  - libopus
  - libpng
  - libpq
  - libsodium
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libvorbis
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libzip
  - lz4-c
  - markupsafe
  - matplotlib-base
  - matplotlib-inline
  - mistune=0.8.4
  - mtz2ccp4_px
  - mysql-common
  - mysql-libs
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook
  - nspr
  - nss
  - numpy
  - ocl-icd
  - ocl-icd-system
  - olefile
  - openbabel
  - openjpeg
  - openmm
  - openssl
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pcre
  - pdbfixer
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - pmw
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - pthread-stubs
  - ptyprocess
  - py3dmol
  - pycairo
  - pycparser
  - pygments
  - pymol
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt-impl
  - pyqt5-sip
  - pyqtchart
  - pyqtwebengine
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pyzmq
  - qt
  - qtconsole
  - qtpy
  - rdkit
  - readline
  - reportlab
  - requests
  - rigimol
  - send2trash
  - setuptools
  - six
  - sqlalchemy
  - sqlite
  - terminado
  - testpath
  - tk
  - tornado
  - traitlets
  - tzdata
  - urllib3
  - vtk-m
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - biopython
    - griddataformats
    - gsd
    - joblib
    - mdanalysis
    - meeko
    - mmtf-python
    - msgpack
    - networkx
    - prolif
    - scipy
    - threadpoolctl
    - tqdm
    - vina
